service: testpokemonspython

frameworkVersion: ">=1.1.0 <=2.8.0"

provider:
  name: aws
  runtime: python3.7
  profile: default
  region: us-east-1

package: 
  individually: true
  # exclude:
  #   - "*/**"

layers:
  dependencies:
    # path: app/shared # required, path to layer contents on disk
    name: pokemons-dependencies # optional, Deployed Lambda layer name
    description: Dependencies
    compatibleRuntimes: # optional, a list of runtimes this layer is compatible with
      - python3.8
      - python3.7
    retain: false # optional, false by default. If true, layer versions are not deleted as new ones are created
    package:
      artifact: app/python.zip

functions:
  ditto:
    handler: app/f1/handler.lambda_handler
    layers:
      - { Ref: DependenciesLambdaLayer }

resources:

  # pikachu:
  #   handler: app/f2/handler.lambda_handler
  #   layers:
  #     - { Ref: DependenciesLambdaLayer }